kind: pipeline
type: docker
name: 构建站点文件

steps:
  - name: pnpm构建
    image: node:18-alpine
    volumes:
      - name: cache
        path: /.pnpm-store
    commands:
      - cat /etc/apk/repositories
      - echo -e 'http://mirrors.jcut.edu.cn/alpine/v3.20/main\nhttp://mirrors.jcut.edu.cn/alpine/v3.20/community' > /etc/apk/repositories
      - apk update && apk add git
      - git version
      - corepack enable
      - corepack use pnpm@10.1.0
      - npx pnpm config set store-dir /.pnpm-store
      - npx pnpm config set registry https://registry.npmmirror.com
      - npx pnpm install --shamefully-hoist
      - npx pnpm run docs:build

volumes:
  - name: cache
    host:
      path: /root/drone/pnpm/cache