kind: pipeline
type: docker
name: 构建站点文件

clone:
  disable: true

steps:
  - name: 拉取代码
    image: alpine/git:latest
    volumes:
      - name: resolv
        path: /etc/resolv.conf
    commands:
      - cat /etc/resolv.conf
      - ping gitea.yupaits.com
  - name: pnpm构建
    image: node:18-alpine
    volumes:
      - name: cache
        path: /.pnpm-store
      - name: dist
        path: /drone/src/docs/.vitepress/dist
    commands:
      - cat /etc/apk/repositories
      - echo -e 'http://mirrors.ustc.edu.cn/alpine/v3.20/main\nhttp://mirrors.ustc.edu.cn/alpine/v3.20/community' > /etc/apk/repositories
      - apk update && apk add git
      - git version
      - npm config set registry https://registry.npmmirror.com
      - npm install -g corepack@latest
      - corepack enable
      - npx pnpm config set store-dir /.pnpm-store
      - npx pnpm config set registry https://registry.npmmirror.com
      - npx pnpm install --shamefully-hoist
      - npx pnpm run docs:build

volumes:
  - name: resolv
    host:
      path: /etc/resolv.conf
  - name: cache
    host:
      path: /volume1/docker/drone/pnpm/cache
  - name: dist
    host:
      path: /volume1/docker/drone/yupaits-notes